### ISSUE TITLE
UniWebView 3 Crashes on startup on Android Unity 5.6.2f1

### ISSUE THREAD

**Issue by dill0wn** [onevcat/UniWebView-Docs#1]
Here is the stacktrace:

```
E/AndroidRuntime(15629): FATAL EXCEPTION: main
E/AndroidRuntime(15629): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime(15629): Unity version     : 5.6.2f1
E/AndroidRuntime(15629): Device model      : LGE Nexus 5
E/AndroidRuntime(15629): Device fingerprint: google/hammerhead/hammerhead:4.4.3/KTU84M/1158763:user/release-keys
E/AndroidRuntime(15629): 
E/AndroidRuntime(15629): Caused by: java.lang.NoSuchMethodError: android.webkit.WebSettings.setMixedContentMode
E/AndroidRuntime(15629): 	at com.onevcat.uniwebview.UniWebView.<init>(UniWebView.java:46)
E/AndroidRuntime(15629): 	at com.onevcat.uniwebview.UniWebViewDialog.addWebViewContent(UniWebViewDialog.java:534)
E/AndroidRuntime(15629): 	at com.onevcat.uniwebview.UniWebViewDialog.<init>(UniWebViewDialog.java:102)
E/AndroidRuntime(15629): 	at com.onevcat.uniwebview.UniWebViewInterface$1.run(UniWebViewInterface.java:114)
E/AndroidRuntime(15629): 	at com.onevcat.uniwebview.UniWebViewInterface$46.run(UniWebViewInterface.java:656)
E/AndroidRuntime(15629): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(15629): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(15629): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(15629): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(15629): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(15629): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(15629): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(15629): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(15629): 	at dalvik.system.NativeStart.main(Native Method)
```
The scene is simple and programmatically instantiates a webview on Awake(). We are using the provided AndroidManifest.xml.

The device is running Android 4.4.3.

**Comment by dill0wn** [comment]
I just tested another device running Android 6.0.1 and it worked fine.

**Comment by happyjiahan** [comment]
same issue in android 4.4.2, same that android.webkit missing some classes in some lower android version

**Comment by onevcat** [comment]
UniWebView 3 supports starting from Android 5.0. So you cannot use it for Android 4.x.

**Comment by mylemans** [comment]
@onevcat Is it just that one call? Or what else is Android 5.0+ only?

**Comment by seyacat** [comment]
if you leave this
#if UNITY_ANDROID && !UNITY_EDITOR

using UnityEngine;

public class UniWebViewInterface {

its imposible use on editor
