### ISSUE TITLE
Class Not Found

### ISSUE THREAD

**Issue by Epiczzor** [onevcat/UniWebView-Docs#12]
Followed installation instructions to the dot, works perfectly on iOS and  getting this error on Android

> AndroidJavaException: java.lang.ClassNotFoundException: com.onevcat.uniwebview.UniWebViewInterface
> 05-10 17:01:36.506 16365 16392 E Unity   : java.lang.ClassNotFoundException: com.onevcat.uniwebview.UniWebViewInterface
> 05-10 17:01:36.506 16365 16392 E Unity   : 	at java.lang.Class.classForName(Native Method)
> 05-10 17:01:36.506 16365 16392 E Unity   : 	at java.lang.Class.forName(Class.java:453)
> 05-10 17:01:36.506 16365 16392 E Unity   : 	at java.lang.Class.forName(Class.java:378)
> 05-10 17:01:36.506 16365 16392 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
> 05-10 17:01:36.506 16365 16392 E Unity   : 	at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
> 05-10 17:01:36.506 16365 16392 E Unity   : 	at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
> 05-10 17:01:36.506 16365 16392 E Unity   : 	at android.os.MessageQueue.next(MessageQueue.java:394)
> 05-10 17:01:36.506 16365 16392 E Unity   : 	at android.os.Looper.loop(Looper.java:142)
> 05-10 17:01:36.506 16365 16392 E Unity   : 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
> 05-10 17:01:36.506 16365 16392 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.onevcat.uniwebview.UniWebViewInterface" on path: DexPathList[[zip file "/data/app/dev.Whatbox.EduQateAndroid-DMAT7r9-RAJFdaayvs90CA==/base.apk"],nativeLibraryDirectories=[/data/app/dev.Whatbox.EduQateAndroid-DMAT7r9-RAJFdaayvs90CA==/lib/arm, /data/app/dev.Whatbox.EduQateAndroid-DMAT7r9-RAJFdaayvs

**Comment by Epiczzor** [comment]
Missing jar file under /plugins/android
